### ISSUE TITLE
SparqlDataset : inconsistent pagination with Blazegraph

### ISSUE THREAD

**Issue by bdecarne** [LinkedDataFragments/Server.js#24]
Hi there,

Pagination is SparqlDatasource is done by a CONSTRUCT with LIMIT/OFFSET. The comments says : 

```
 // Even though the SPARQL spec indicates that
 // LIMIT and OFFSET might be meaningless without ORDER BY,
 // this doesn't seem a problem in practice.
 // Furthermore, sorting can be slow. Therefore, don't sort.
```

When i use Blazegraph SPARQL Endpoint, it's a problem in practice : order is not garantee without ORDER BY. I experimented it by get differents results for the same page.

I use a 4B triplets dataset, and the use of a ORDER BY is not possible due to a performance consideration.

This is a limitation of the LDF concept over SPARQL Endpoint : it's based on a false SPARQL assumption ("this doesn't seem a problem in practice.").

What are your feelings on this point ?

Bests,
Blaise

**Comment by RubenVerborgh** [comment]
Hi Blaise,

Fortunately, it's not a limitation of the Triple Pattern Fragments concept, but rather a limitation of this implementation. As you mention, it is not easy to fix because of the performance of some endpoints.

We could have a configuration option to switch sorting on or off, but I'm afraid that wouldn't help in your case either.

Might be worthwhile to check with Blazegraph whether they have a suggestion for this.

Best,

Ruben

**Comment by bdecarne** [comment]
Ruben,

Thank you for your answer. Your right, i made a post on the Blazegraph mailing list.

Blaise
