### ISSUE TITLE
Docker: smaller image

### ISSUE THREAD

**Issue by barthanssens** [LinkedDataFragments/Server.js#40]
Current docker image is about 700 MB, a smaller image would be nice for running Server.js on cheap virtual servers / instances.

Testing with alpine didn't seem to work when HDT is needed (after adding a few packages and successfully compiling hdt.node, there are quite a lot of missing symbols at runtime, adding libuv and libstdc++ packages didn't help). 

See also comments at bottom of #19 , where it is explained that this could be  due to Alpine using musl-libc instead of glibc

**Comment by thadguidry** [comment]
@barthanssens Alpine doesn't use glibc, but instead musl libc. This makes it smaller, but you might run into build problems if glibc is necessary for some of the libraries. Remember, Alpine was created primarily to support running on small embedded devices. Its not always a good first choice for larger applications. But Docker has now officially embraced it. Regardless, you should be able to "get regular stuff working"
https://alpinelinux.org/posts/Alpine-Linux-has-switched-to-musl-libc.html
https://wiki.alpinelinux.org/wiki/How_to_get_regular_stuff_working
https://wiki.alpinelinux.org/wiki/Upgrading_Alpine

**Comment by thadguidry** [comment]
@barthanssens I also wanted to share with you some best practices with Java Docker, and avoid the bad tutorials out there that unintentionally encourage some Docker bad practices. https://codefresh.io/blog/java_docker_pipeline/

**Comment by rubensworks** [comment]
Starting from alpine indeed seems to be a bit tricky...

An alternative solution would be to start from the `scratch`, and build our way up from there, i.e. adding node, gcc, ...
This might require a bit more work, but will lead to even smaller images.

**Comment by RubenVerborgh** [comment]
What is the main size contributor to the image?

**Comment by rubensworks** [comment]
The LDF server itself should be around 20~30 MB including dependencies, node-alpine is ~42MB, so theoretically we could have image sizes of ~70MB.

The current node base image however is 655.6 MB, because of the large image size they inherit from `buildpack-deps:jessie` (610.1 MB). The main size contributor is all the software that is installed by-default in this image.

We do however see the immediate advantages of this larger base image, installing/running any kind of software (such as HDT)will just work in most of the cases.

**Comment by thadguidry** [comment]
@rubensworks Don't necessarily treat Docker as a desktop.  Treat Docker as the minimal viable container to ship and run your application(s).  Just think how your typical user base will be running and deploying things.  Will 80% of your user base often have a need to run HDT in addition ? http://rhelblog.redhat.com/2016/03/16/container-tidbits-when-should-i-break-my-application-into-multiple-containers/

**Comment by rubensworks** [comment]
@thadguidry You're right, Docker images should be as small as possible. This unfortunately is not as simple as it sounds as we have experienced.

Regarding the HDT-aspect, I would say yes, most people will run the LDF server using HDT. That is because all datasource types (except for HDT) will load all data into memory, which doesn't scale for large datasets. HDT instead performs memory-mapping, which makes it possible to load datasets of any size. Additionally, it allows very efficient (triple pattern) queries, which is ideal for TPF.

In the rare cases that HDT is not required, a slimmed-down version of the LDF server Docker image could indeed be made available. But I'm not sure if there would be any demand for that.

**Comment by thadguidry** [comment]
@rubensworks Then you have your answer :)  Add HDT and its dependencies to the Docker image as well :)
And when this Docker image is ready, I plan to be one of those users.  I have so much data to give away :)

**Comment by rubensworks** [comment]
@thadguidry That is exactly what we are currently doing :-)
HDT is (indirectly) being installed as an [NPM dependency](https://github.com/RubenVerborgh/HDT-Node/).

This (HDT-enabled) Docker image is available on the [Docker hub](https://hub.docker.com/r/linkeddatafragments/server.js/), so you can already start using it! :-)

**Comment by thadguidry** [comment]
@rubensworks Cool.  I'll start serving stuff probably beginning this weekend.  I'll ping the team if I have any issues.

**Comment by rubensworks** [comment]
Resolved by #58
