### ISSUE TITLE
Possible to mimic sparql endpoint with LDF server?

### ISSUE THREAD

**Issue by mathib** [LinkedDataFragments/Server.js#80]
Hi, I'm new to LDF but I can see the advantages regarding easy sharing of Linked Data (definitely in a research context) without the headaches of having to set up a server for a sparql endpoint.

In my situation, I have an application that expects either an open sparql endpoint (e.g. dbpedia) or a local sparql endpoint (e.g. virtuoso/stardog/... running on localhost on the same server as the app). I want to share my own sample RDF with users and therefore it has to be hosted on a simple webserver such as Heroku or ghpages.

Is their an easy way to 'fool' my application in thinking it is communicating with a regular open sparql endpoint, instead of a LDF endpoint by using this LDF server? In this way, it would also be straightforward to do federated querying over LDF endpoints from a regular sparql endpoint, I assume.

**Comment by RubenVerborgh** [comment]
> Is their an easy way to 'fool' my application in thinking it is communicating with a regular open sparql endpoint, instead of a LDF endpoint by using this LDF server?

For a local app, you can use the `bin/ldf-client-http` example from the Client.js repository. This will expose the LDF client through a SPARQL endpoint interface.

However, only use this on localhost. It is purely intended for internal or benchmarking purposes. If you put this publicly, you will have a SPARQL endpoint that suffers from all the problems of existing public SPARQL endpoints, and even more so because it is not running an actual database behind it.

> In this way, it would also be straightforward to do federated querying over LDF endpoints from a regular sparql endpoint, I assume.

Yes, but it will be slow. Instead, you want to federate over LDF endpoints using the LDF client.

**Comment by mathib** [comment]
Hi Ruben, thanks for the clear explanation. I'm planning to use it for a small demo dataset I can share over the web (I guess around 300 triples), and the nice thing would be that I don't have to adapt the web app, which is made for sparql endpoints that run locally. In this way, people don't have to install a triplestore just to quickly check out the app. But indeed, I'll have to check if it's not becoming too slow at the end.

From a practical point of view, I was thinking to deploy the server.js as a Heroku app (which is also slow in free mode), but then I guess I have to make a second Heroku app for the `ldf-client-http`

**Comment by RubenVerborgh** [comment]
> I guess around 300 triples

I don't think you'll run into any problems then :-)
