### ISSUE TITLE
More than 100 results per page

### ISSUE THREAD

**Issue by harej** [LinkedDataFragments/Server.js#82]
Wikidata, a project which produces an RDF graph queryable over SPARQL and LDF endpoints, has over 13 million entries for journal articles with DOIs. At 100 results per page, it would require over 130,000 requests to get each page of results. Being able to get more results per page would decrease the HTTP overhead a lot.

**Comment by rubensworks** [comment]
The LDF server supports changing the `pageSize` via the config file.

Here you can see an example: https://github.com/LinkedDataFragments/Server.js/blob/a1e7dbe28b51f4967166dca957701abe21776e73/config/config-example-advanced.json#L31

**Comment by harej** [comment]
Is it possible for the user to define a custom page size? One hundred results per page makes sense for loading in the browser, for example, but for my automated retrievals I'd like to pull as many as possible at a time. This is where having a user-defined page size would be helpful (and probably better captures what I meant to ask with this Issue).

**Comment by rubensworks** [comment]
No, only the server can decide what the page size is.

If we'd allow clients to define a custom page size, this could increase server load due to the additional parameter that gets added, which would be unfavourable for caching.

If one client would for example query things with a page size of 100, and another client would query with page size 1000, then the server (and any intermediaries) would not be able to cache the result pages. This is the main reason why we limit the exposed parameters.

**Comment by RubenVerborgh** [comment]
While it is possible to change the page size of the server, we have found in experiments that it doesn't make _that_ much of a difference as one would think.

When executing queries, the size of the first page seemed to make a difference, but that of the remaining pages not really.

Also note that, with HTTP/2, the overhead and hence the difference becomes really minimal.

**Comment by rubensworks** [comment]
Considering this resolved, please comment should this not be the case.
