### ISSUE TITLE
Some object page with generated ID not working

### ISSUE THREAD

**Issue by miranda-zhang** [LinkedDataFragments/Server.js#91]
I have the following page on my server:
http://35.231.131.100:5000/cocoon_v1.0.1?object=genid%3Acocoon_v1.0.1%2Fb827

When I clicked on **b827**, it didn't go anywhere.

I'm expecting to see some object page generated for data looks like this:
```
        gr:hasPriceSpecification        [ a                        gr:CloudServicePriceSpecification ;
                                          gr:hasCurrency           "USD" ;
                                          gr:hasCurrencyValue      "135.17e0"^^xsd:float ;
                                          gr:hasUnitOfMeasurement  cocoon:GBPerMonth ;
                                          cocoon:inRegion          <https://w3id.org/cocoon/data/v1.0.1/Region/Azure/europe-north>
                                        ] ;
```
My data can be viewed here
https://github.com/miranda-zhang/cloud-computing-schema/blob/099d345ae1bf4d5b766931a877de0a5239a59cfc/v1.0.1/azure/v1.0.1/2019-03-07/managed-disks.ttl#L6657

**Comment by rubensworks** [comment]
> When I clicked on b827, it didn't go anywhere.

Since this blank node appears in the _object_ position of your triple, clicking on it will trigger a triple pattern request for that given object.
As such, this works as intended.

I assume you want that blank node in the subject position.
For this, you can query the following pattern:
http://35.231.131.100:5000/cocoon_v1.0.1?subject=genid%3Acocoon_v1.0.1%2Fb827&predicate=&object=

**Comment by miranda-zhang** [comment]
Thank you so much for clarifying!
